# Generated by Django 4.0.2 on 2022-03-02 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('location', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('month', models.IntegerField(default=0)),
                ('month7', models.IntegerField(default=0)),
                ('month8', models.IntegerField(default=0)),
                ('month9', models.IntegerField(default=0)),
                ('month10', models.IntegerField(default=0)),
            ],
        ),
    ]
