# Generated by Django 4.0.2 on 2022-02-22 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('m_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('m_pw', models.CharField(max_length=30)),
                ('m_name', models.CharField(max_length=30)),
            ],
        ),
    ]
